#! /bin/sh

feh --bg-scale /etc/lightdm/background.png
setxkbmap gb,ru -option grp:win_space_toggle
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
